# apiVersion: v1
# kind: Namespace
# metadata:
#   name: demo
# ---
apiVersion: demo.demo.daniele.io/v1
kind: DemoVolume
metadata:
  labels:
    app.kubernetes.io/name: demovolume
    app.kubernetes.io/instance: demovolume-sample
    app.kubernetes.io/part-of: k8s-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-test
  name: demovolume-sample
  # namespace: k8s-test-system
spec:
  # TODO(user): Add fields here
  containerId: nginx
  containerTag: latest
